### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Erica1217** [rlatjdfo112/LockScreenApplication#1]

**Comment by Erica1217** [comment]
`import React, { Component } from 'react';
import { Text, View, StyleSheet } from 'react-native';
import { Constants } from 'expo';

export default class App extends Component {
  render() {
    return (
      <View>
        <Navigation/>
      </View>
    );
  }
}

class Navigation extends Component{
  render(){
    return (
      <View style={styles.navBar}>
        <NavButton buttonName="타임라인"/>
        <NavButton buttonName="친구목록"/>
        <NavButton buttonName="최신소식"/>
        <NavButton buttonName="기타"/>
        
      </View>
      )
  }
}

class NavButton extends Component{
  render(){
    return(
      <View style={styles.navButton}>
        <View style={styles.navButtonLogo}>
          <Text>{this.props.buttonName}</Text>
        </View>
      </View>
      
      )
  }
}

const styles = StyleSheet.create({
  navBar:{
    height:60,
    justifyContent:'center',
    alignItems:'center',
    flexDirection:'row',
    borderWidth:0.5
  },
  navButton:{
    flex:1,
    justifyContent:'center',
    alignItems:'center'
  },
  navButtonLogo:{
    height:50,
    width:50,
    backgroundColor:'gray'
  }
});`

**Comment by Erica1217** [comment]
```
import React, { Component } from 'react';
import { Text, View, StyleSheet } from 'react-native';
import { Constants } from 'expo';

export default class App extends Component {
  render() {
    return (
      <View>
        <Navigation/>
      </View>
    );
  }
}

class Navigation extends Component{
  render(){
    return (
      <View style={styles.navBar}>
        <NavButton buttonName="타임라인"/>
        <NavButton buttonName="친구목록"/>
        <NavButton buttonName="최신소식"/>
        <NavButton buttonName="기타"/>
        
      </View>
      )
  }
}

class NavButton extends Component{
  render(){
    return(
      <View style={styles.navButton}>
        <View style={styles.navButtonLogo}>
          <Text>{this.props.buttonName}</Text>
        </View>
      </View>
      
      )
  }
}

const styles = StyleSheet.create({
  navBar:{
    height:60,
    justifyContent:'center',
    alignItems:'center',
    flexDirection:'row',
    borderWidth:0.5
  },
  navButton:{
    flex:1,
    justifyContent:'center',
    alignItems:'center'
  },
  navButtonLogo:{
    height:50,
    width:50,
    backgroundColor:'gray'
  }
});
```

**Comment by boxfox619** [comment]
``
